services:
  app:
    image: app
    restart: always
    ports:
      - 3000:3333
    environment:
      PASSWORD: 1
      USER: mai
      DBNAME: researchdocument
      HOST: db
      PORT: 5432
      TIMEZONE: ASIA/Ho_Chi_Minh
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: mai
      POSTGRES_DB: researchdocument
    volumes:
      - db-save:/var/lib/postgresql/data
volumes:
  db-save: