output   = "./internal/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
dbname = "researchdocument"
host   = "localhost"
port   = 5432
user   = "mai"
pass   = "1"
sslmode = "disable"
schema = "main"

# Although team_names works fine without configuration, we use it here for illustrative purposes
[aliases.tables.DocumentItem]
up_plural     = "DocumentItems"
up_singular   = "DocumentItem"
down_plural   = "documentItems"
down_singular = "documentItem"
# Columns can also be aliased.
[aliases.tables.DocumentItem.columns]
DocumentItemId = "DocumentItemID"
CreatedAt="CreatedAt"


[aliases.tables.Document]
up_plural     = "Documents"
up_singular   = "Document"
down_plural   = "documents"
down_singular = "document"
# Columns can also be aliased.
[aliases.tables.Document.columns]
DocumentId = "DocumentID"
CreatedAt = "CreatedAt"