// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SubDocument is an object representing the database table.
type SubDocument struct {
	subDocumentId string      `boil:"subdocumentid" json:"subdocumentid" toml:"subdocumentid" yaml:"subdocumentid"`
	Title         null.String `boil:"title" json:"title,omitempty" toml:"title" yaml:"title,omitempty"`
	Createdat     null.Time   `boil:"createdat" json:"createdat,omitempty" toml:"createdat" yaml:"createdat,omitempty"`
	Content       null.String `boil:"content" json:"content,omitempty" toml:"content" yaml:"content,omitempty"`
	Documentid    null.String `boil:"documentid" json:"documentid,omitempty" toml:"documentid" yaml:"documentid,omitempty"`

	R *subDocumentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L subDocumentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SubDocumentColumns = struct {
	subDocumentId string
	Title         string
	Createdat     string
	Content       string
	Documentid    string
}{
	subDocumentId: "subdocumentid",
	Title:         "title",
	Createdat:     "createdat",
	Content:       "content",
	Documentid:    "documentid",
}

var SubDocumentTableColumns = struct {
	subDocumentId string
	Title         string
	Createdat     string
	Content       string
	Documentid    string
}{
	subDocumentId: "subdocument.subdocumentid",
	Title:         "subdocument.title",
	Createdat:     "subdocument.createdat",
	Content:       "subdocument.content",
	Documentid:    "subdocument.documentid",
}

// Generated where

var SubDocumentWhere = struct {
	subDocumentId whereHelperstring
	Title         whereHelpernull_String
	Createdat     whereHelpernull_Time
	Content       whereHelpernull_String
	Documentid    whereHelpernull_String
}{
	subDocumentId: whereHelperstring{field: "\"main\".\"subdocument\".\"subdocumentid\""},
	Title:         whereHelpernull_String{field: "\"main\".\"subdocument\".\"title\""},
	Createdat:     whereHelpernull_Time{field: "\"main\".\"subdocument\".\"createdat\""},
	Content:       whereHelpernull_String{field: "\"main\".\"subdocument\".\"content\""},
	Documentid:    whereHelpernull_String{field: "\"main\".\"subdocument\".\"documentid\""},
}

// SubDocumentRels is where relationship names are stored.
var SubDocumentRels = struct {
	DocumentidDocument string
}{
	DocumentidDocument: "DocumentidDocument",
}

// subDocumentR is where relationships are stored.
type subDocumentR struct {
	DocumentidDocument *Document `boil:"DocumentidDocument" json:"DocumentidDocument" toml:"DocumentidDocument" yaml:"DocumentidDocument"`
}

// NewStruct creates a new relationship struct
func (*subDocumentR) NewStruct() *subDocumentR {
	return &subDocumentR{}
}

func (r *subDocumentR) GetDocumentidDocument() *Document {
	if r == nil {
		return nil
	}
	return r.DocumentidDocument
}

// subDocumentL is where Load methods for each relationship are stored.
type subDocumentL struct{}

var (
	subDocumentAllColumns            = []string{"subdocumentid", "title", "createdat", "content", "documentid"}
	subDocumentColumnsWithoutDefault = []string{}
	subDocumentColumnsWithDefault    = []string{"subdocumentid", "title", "createdat", "content", "documentid"}
	subDocumentPrimaryKeyColumns     = []string{"subdocumentid"}
	subDocumentGeneratedColumns      = []string{}
)

type (
	// SubDocumentSlice is an alias for a slice of pointers to SubDocument.
	// This should almost always be used instead of []SubDocument.
	SubDocumentSlice []*SubDocument
	// SubDocumentHook is the signature for custom SubDocument hook methods
	SubDocumentHook func(context.Context, boil.ContextExecutor, *SubDocument) error

	subDocumentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	subDocumentType                 = reflect.TypeOf(&SubDocument{})
	subDocumentMapping              = queries.MakeStructMapping(subDocumentType)
	subDocumentPrimaryKeyMapping, _ = queries.BindMapping(subDocumentType, subDocumentMapping, subDocumentPrimaryKeyColumns)
	subDocumentInsertCacheMut       sync.RWMutex
	subDocumentInsertCache          = make(map[string]insertCache)
	subDocumentUpdateCacheMut       sync.RWMutex
	subDocumentUpdateCache          = make(map[string]updateCache)
	subDocumentUpsertCacheMut       sync.RWMutex
	subDocumentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var subDocumentAfterSelectHooks []SubDocumentHook

var subDocumentBeforeInsertHooks []SubDocumentHook
var subDocumentAfterInsertHooks []SubDocumentHook

var subDocumentBeforeUpdateHooks []SubDocumentHook
var subDocumentAfterUpdateHooks []SubDocumentHook

var subDocumentBeforeDeleteHooks []SubDocumentHook
var subDocumentAfterDeleteHooks []SubDocumentHook

var subDocumentBeforeUpsertHooks []SubDocumentHook
var subDocumentAfterUpsertHooks []SubDocumentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SubDocument) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SubDocument) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SubDocument) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SubDocument) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SubDocument) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SubDocument) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SubDocument) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SubDocument) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SubDocument) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range subDocumentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSubDocumentHook registers your hook function for all future operations.
func AddSubDocumentHook(hookPoint boil.HookPoint, subDocumentHook SubDocumentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		subDocumentAfterSelectHooks = append(subDocumentAfterSelectHooks, subDocumentHook)
	case boil.BeforeInsertHook:
		subDocumentBeforeInsertHooks = append(subDocumentBeforeInsertHooks, subDocumentHook)
	case boil.AfterInsertHook:
		subDocumentAfterInsertHooks = append(subDocumentAfterInsertHooks, subDocumentHook)
	case boil.BeforeUpdateHook:
		subDocumentBeforeUpdateHooks = append(subDocumentBeforeUpdateHooks, subDocumentHook)
	case boil.AfterUpdateHook:
		subDocumentAfterUpdateHooks = append(subDocumentAfterUpdateHooks, subDocumentHook)
	case boil.BeforeDeleteHook:
		subDocumentBeforeDeleteHooks = append(subDocumentBeforeDeleteHooks, subDocumentHook)
	case boil.AfterDeleteHook:
		subDocumentAfterDeleteHooks = append(subDocumentAfterDeleteHooks, subDocumentHook)
	case boil.BeforeUpsertHook:
		subDocumentBeforeUpsertHooks = append(subDocumentBeforeUpsertHooks, subDocumentHook)
	case boil.AfterUpsertHook:
		subDocumentAfterUpsertHooks = append(subDocumentAfterUpsertHooks, subDocumentHook)
	}
}

// One returns a single subDocument record from the query.
func (q subDocumentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SubDocument, error) {
	o := &SubDocument{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for subdocument")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SubDocument records from the query.
func (q subDocumentQuery) All(ctx context.Context, exec boil.ContextExecutor) (SubDocumentSlice, error) {
	var o []*SubDocument

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SubDocument slice")
	}

	if len(subDocumentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SubDocument records in the query.
func (q subDocumentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count subdocument rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q subDocumentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if subdocument exists")
	}

	return count > 0, nil
}

// DocumentidDocument pointed to by the foreign key.
func (o *SubDocument) DocumentidDocument(mods ...qm.QueryMod) documentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"documentid\" = ?", o.Documentid),
	}

	queryMods = append(queryMods, mods...)

	return Documents(queryMods...)
}

// LoadDocumentidDocument allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (subDocumentL) LoadDocumentidDocument(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSubDocument interface{}, mods queries.Applicator) error {
	var slice []*SubDocument
	var object *SubDocument

	if singular {
		object = maybeSubDocument.(*SubDocument)
	} else {
		slice = *maybeSubDocument.(*[]*SubDocument)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &subDocumentR{}
		}
		if !queries.IsNil(object.Documentid) {
			args = append(args, object.Documentid)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &subDocumentR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.Documentid) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.Documentid) {
				args = append(args, obj.Documentid)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`main.document`),
		qm.WhereIn(`main.document.documentid in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Document")
	}

	var resultSlice []*Document
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Document")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for document")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for document")
	}

	if len(subDocumentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DocumentidDocument = foreign
		if foreign.R == nil {
			foreign.R = &documentR{}
		}
		foreign.R.DocumentidSubdocuments = append(foreign.R.DocumentidSubdocuments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.Documentid, foreign.DocumentId) {
				local.R.DocumentidDocument = foreign
				if foreign.R == nil {
					foreign.R = &documentR{}
				}
				foreign.R.DocumentidSubdocuments = append(foreign.R.DocumentidSubdocuments, local)
				break
			}
		}
	}

	return nil
}

// SetDocumentidDocument of the subDocument to the related item.
// Sets o.R.DocumentidDocument to related.
// Adds o to related.R.DocumentidSubdocuments.
func (o *SubDocument) SetDocumentidDocument(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Document) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"main\".\"subdocument\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"documentid"}),
		strmangle.WhereClause("\"", "\"", 2, subDocumentPrimaryKeyColumns),
	)
	values := []interface{}{related.DocumentId, o.subDocumentId}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.Documentid, related.DocumentId)
	if o.R == nil {
		o.R = &subDocumentR{
			DocumentidDocument: related,
		}
	} else {
		o.R.DocumentidDocument = related
	}

	if related.R == nil {
		related.R = &documentR{
			DocumentidSubdocuments: SubDocumentSlice{o},
		}
	} else {
		related.R.DocumentidSubdocuments = append(related.R.DocumentidSubdocuments, o)
	}

	return nil
}

// RemoveDocumentidDocument relationship.
// Sets o.R.DocumentidDocument to nil.
// Removes o from all passed in related items' relationships struct.
func (o *SubDocument) RemoveDocumentidDocument(ctx context.Context, exec boil.ContextExecutor, related *Document) error {
	var err error

	queries.SetScanner(&o.Documentid, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("documentid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.DocumentidDocument = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.DocumentidSubdocuments {
		if queries.Equal(o.Documentid, ri.Documentid) {
			continue
		}

		ln := len(related.R.DocumentidSubdocuments)
		if ln > 1 && i < ln-1 {
			related.R.DocumentidSubdocuments[i] = related.R.DocumentidSubdocuments[ln-1]
		}
		related.R.DocumentidSubdocuments = related.R.DocumentidSubdocuments[:ln-1]
		break
	}
	return nil
}

// SubDocuments retrieves all the records using an executor.
func SubDocuments(mods ...qm.QueryMod) subDocumentQuery {
	mods = append(mods, qm.From("\"main\".\"subdocument\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"main\".\"subdocument\".*"})
	}

	return subDocumentQuery{q}
}

// FindSubDocument retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSubDocument(ctx context.Context, exec boil.ContextExecutor, subDocumentId string, selectCols ...string) (*SubDocument, error) {
	subDocumentObj := &SubDocument{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"main\".\"subdocument\" where \"subdocumentid\"=$1", sel,
	)

	q := queries.Raw(query, subDocumentId)

	err := q.Bind(ctx, exec, subDocumentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from subdocument")
	}

	if err = subDocumentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return subDocumentObj, err
	}

	return subDocumentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SubDocument) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no subdocument provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(subDocumentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	subDocumentInsertCacheMut.RLock()
	cache, cached := subDocumentInsertCache[key]
	subDocumentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			subDocumentAllColumns,
			subDocumentColumnsWithDefault,
			subDocumentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(subDocumentType, subDocumentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(subDocumentType, subDocumentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"main\".\"subdocument\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"main\".\"subdocument\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into subdocument")
	}

	if !cached {
		subDocumentInsertCacheMut.Lock()
		subDocumentInsertCache[key] = cache
		subDocumentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SubDocument.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SubDocument) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	subDocumentUpdateCacheMut.RLock()
	cache, cached := subDocumentUpdateCache[key]
	subDocumentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			subDocumentAllColumns,
			subDocumentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update subdocument, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"main\".\"subdocument\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, subDocumentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(subDocumentType, subDocumentMapping, append(wl, subDocumentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update subdocument row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for subdocument")
	}

	if !cached {
		subDocumentUpdateCacheMut.Lock()
		subDocumentUpdateCache[key] = cache
		subDocumentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q subDocumentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for subdocument")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for subdocument")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SubDocumentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), subDocumentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"main\".\"subdocument\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, subDocumentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in subDocument slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all subDocument")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SubDocument) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no subdocument provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(subDocumentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	subDocumentUpsertCacheMut.RLock()
	cache, cached := subDocumentUpsertCache[key]
	subDocumentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			subDocumentAllColumns,
			subDocumentColumnsWithDefault,
			subDocumentColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			subDocumentAllColumns,
			subDocumentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert subdocument, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(subDocumentPrimaryKeyColumns))
			copy(conflict, subDocumentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"main\".\"subdocument\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(subDocumentType, subDocumentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(subDocumentType, subDocumentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert subdocument")
	}

	if !cached {
		subDocumentUpsertCacheMut.Lock()
		subDocumentUpsertCache[key] = cache
		subDocumentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SubDocument record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SubDocument) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SubDocument provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), subDocumentPrimaryKeyMapping)
	sql := "DELETE FROM \"main\".\"subdocument\" WHERE \"subdocumentid\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from subdocument")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for subdocument")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q subDocumentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no subDocumentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from subdocument")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for subdocument")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SubDocumentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(subDocumentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), subDocumentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"main\".\"subdocument\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, subDocumentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from subDocument slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for subdocument")
	}

	if len(subDocumentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SubDocument) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSubDocument(ctx, exec, o.subDocumentId)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SubDocumentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SubDocumentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), subDocumentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"main\".\"subdocument\".* FROM \"main\".\"subdocument\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, subDocumentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SubDocumentSlice")
	}

	*o = slice

	return nil
}

// SubDocumentExists checks if the SubDocument row exists.
func SubDocumentExists(ctx context.Context, exec boil.ContextExecutor, subDocumentId string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"main\".\"subdocument\" where \"subdocumentid\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, subDocumentId)
	}
	row := exec.QueryRowContext(ctx, sql, subDocumentId)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if subdocument exists")
	}

	return exists, nil
}
