// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	models "s3corp-golang-fresher/internal/models"

	mock "github.com/stretchr/testify/mock"

	utils "s3corp-golang-fresher/utils"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: user
func (_m *UserService) CreateUser(user models.User) utils.Error {
	ret := _m.Called(user)

	var r0 utils.Error
	if rf, ok := ret.Get(0).(func(models.User) utils.Error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(utils.Error)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: username
func (_m *UserService) DeleteUser(username string) utils.Error {
	ret := _m.Called(username)

	var r0 utils.Error
	if rf, ok := ret.Get(0).(func(string) utils.Error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(utils.Error)
	}

	return r0
}

// GetUserByUsername provides a mock function with given fields: username
func (_m *UserService) GetUserByUsername(username string) (*models.User, utils.Error) {
	ret := _m.Called(username)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 utils.Error
	if rf, ok := ret.Get(1).(func(string) utils.Error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Get(1).(utils.Error)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields:
func (_m *UserService) GetUsers() (models.UserSlice, utils.Error) {
	ret := _m.Called()

	var r0 models.UserSlice
	if rf, ok := ret.Get(0).(func() models.UserSlice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.UserSlice)
		}
	}

	var r1 utils.Error
	if rf, ok := ret.Get(1).(func() utils.Error); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(utils.Error)
	}

	return r0, r1
}

// Login provides a mock function with given fields: username, password
func (_m *UserService) Login(username string, password string) (*models.User, utils.Error) {
	ret := _m.Called(username, password)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string, string) *models.User); ok {
		r0 = rf(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 utils.Error
	if rf, ok := ret.Get(1).(func(string, string) utils.Error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Get(1).(utils.Error)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: user
func (_m *UserService) UpdateUser(user models.User) utils.Error {
	ret := _m.Called(user)

	var r0 utils.Error
	if rf, ok := ret.Get(0).(func(models.User) utils.Error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(utils.Error)
	}

	return r0
}

type mockConstructorTestingTNewUserService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserService(t mockConstructorTestingTNewUserService) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
